server:
  port: 8125
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ms-transaction
        uri: lb://ms-transaction
        predicates:
        - Path=/transaction/**
      - id: ms-stock
        uri: lb://ms-stock
        predicates:
        - Path=/stock/**